### ISSUE TITLE
Webmanifest cannot find page on inserting meta data

### ISSUE THREAD

**Issue by ashhitch** [alextim/astro-lib#65]
Hitting an issue when the plugin is inserting the meta links it tries to find a page of `500/index.html` however Astro as generated `500.html`

Disabling the inserting meta links fixes the issue. 

running Astro `4.15.3`

Here is the stack trace:
```
8:59:15 AM: astro-webmanifest: `manifest.webmanifest` is created.
8:59:15 AM: ENOENT: no such file or directory, open '/opt/build/repo/dist/500/index.html'
8:59:15 AM:   Stack trace:
8:59:15 AM:     at async open (node:internal/fs/promises:639:25)
8:59:15 AM:     at async processPages (file:///opt/build/repo/node_modules/.pnpm/astro-webmanifest@1.0.0/node_modules/astro-webmanifest/dist/index.js:491:21)
8:59:15 AM:     at async astro:build:done (file:///opt/build/repo/node_modules/.pnpm/astro-webmanifest@1.0.0/node_modules/astro-webmanifest/dist/index.js:606:11)
8:59:15 AM:     at async runHookBuildDone (file:///opt/build/repo/node_modules/.pnpm/astro@4.15.3_@types+node@22.5.1_typescript@5.5.4/node_modules/astro/dist/integrations/hooks.js:428:7)
8:59:15 AM:     at async AstroBuilder.run (file:///opt/build/repo/node_modules/.pnpm/astro@4.15.3_@types+node@22.5.1_typescript@5.5.4/node_modules/astro/dist/core/build/index.js:180:7)
```

**Comment by chriswthomson** [comment]
I'm also seeing this, running 5.0.0-beta.4 deploying to Netlify.
